// export const SET_SINGLE_VIEW_ENABLE = "SET_SINGLE_VIEW_ENABLE";
// export const SET_SINGLE_VIEW_DISABLE = "SET_SINGLE_VIEW_DISABLE";
// export const REGION_DATA = "REGION_DATA";
// export const SET_MASTER_ENTITIES = "SET_MASTER_ENTITIES";
// export const SET_ALL_COUNTRIES = "SET_ALL_COUNTRIES";
// export const SET_EMISSION_SCOPES_SINGLE = "EMISSION SCOPES";
// export const SET_EMISSION_TIMELINE_SINGLE = "EMISSION TIMELINE";
// export const SET_EMISSION_GHG_SINGLE = "GHG WISE EMISSION";
// export const SET_EMISSION_ACTIVITY_SINGLE = "EMISSION ACROSS ACTIVITY";
// export const SET_EMISSION_SUPPLIER_SINGLE = "EMISSION BY SUPPLIER";
// export const SET_EMISSION_SALES_SINGLE = "SALES VS EMISSION";
// export const SET_EMISSION_TRANSPORTATION_SINGLE =
//   "EMISSION ACROSS TRANSPORTATION";
// export const COST_FUEL_ITEM_SHIPPED_EMISSION =
//   "COST_FUEL_ITEM_SHIPPED_EMISSION";
// export const LANES_SINGLE = "LANES VS EMISSION";
// export const CONTINENT_SINGLE = "CONTINENT VS EMISSION";
// export const PROCESS_SINGLE = "PROCESS VS EMISSIONS";
// export const EMISSION_SINGLE = "EMISSION PERFORMANCE";
// export const MODES_SINGLE = "MODES VS EMISSION";
// export const PRODUCT_TYPE_VS_EMISSION_SINGLE = "PRODUCT TYPE VS EMISSIONS";
// export const SUPPLIER_SINGLE = "SUPPLIER VS EMISSIONS";
// export const SET_EMISSION_REGION_SINGLE = "EMISSION BY REGION";
// export const SET_EMISSION_COUNTRY_SINGLE = "EMISSION BY COUNTRY";
// export const SET_ADD_GRAPH = "SET_ADD_GRAPH";
// export const SET_EDIT_GRAPH = "SET_EDIT_GRAPH";
// export const SET_SINGLE_DETAILED = "SET_SINGLE_DETAILED";
// export const SET_SINGLE_EXECUTIVE = "SET_SINGLE_EXECUTIVE";
// export const SET_EMISSION_REGION_DETAILED_SINGLE = "EMISSION BY REGION DETAILED";
// export const SET_EMISSION_COUNTRY_DETAILED_SINGLE = "EMISSION BY COUNTRY DETAILED";
// export const TOTAL_SCOPE_1_EMISSION_VS_CATEGORIES = "TOTAL SCOPE-1 EMISSION VS CATEGORIES";
// export const TOTAL_SCOPE_2_EMISSION_VS_CATEGORIES = "TOTAL SCOPE-2 EMISSION VS CATEGORIES";
// export const TOTAL_SCOPE_3_EMISSION_VS_CATEGORIES = "TOTAL SCOPE-3 EMISSION VS CATEGORIES";
// export const TOTAL_EMISSION_COSTFUEL = "TOTAL_EMISSION_COSTFUEL";
// export const UPSTREAM_NETWORKS_VS_EMISSION = "UPSTREAM NETWORKS VS EMISSION";
// export const DOWNSTREAM_ASSET_TYPE_VS_EMISSION = "DOWNSTREAM ASSET TYPE VS EMISSION";
// export const DOWNSTREAM_LESSEE_VS_EMISSION = "DOWNSTREAM LESSEE VS EMISSION";
// export const UPSTREAM_ASSET_TYPE_VS_EMISSION = "UPSTREAM ASSET TYPE VS EMISSION";
// export const UPSTREAM_LESSOR_VS_EMISSION = "UPSTREAM LESSOR VS EMISSION";
// export const RMPO_WISE_EMISSIONS = "RMPO WISE EMISSIONS";
// export const NON_SCM_SOURCING_VS_EMISSION = "NON SCM SOURCING VS EMISSION";
// export const FRANCHISE_WISE_EMISSION = "FRANCHISE WISE EMISSION";
// export const DOWNSTREAM_WASTE_MANAGEMENT_VS_EMISSION = "DOWNSTREAM WASTE MANAGEMENT VS EMISSION";
// export const UPSTREAM_WASTE_MANAGEMENT_VS_EMISSION = "UPSTREAM WASTE MANAGEMENT VS EMISSION";
// export const DEDICATED_VEHICLE_TYPE_VS_EMISSION = "DEDICATED VEHICLE TYPE VS EMISSIONS";
// export const OUTSOURCED_VEHICLE_TYPE_VS_EMISSION = "OUTSOURCED VEHICLE TYPE VS EMISSIONS";
// export const WASTE_PROCESSING_COMPANIES_VS_EMISSION = "WASTE PROCESSING COMPANIES VS EMISSIONS"
// export const SOLD_PRODUCTS_VS_EMISSION = "SOLD PRODUCTS VS EMISSIONS";
// export const REFRIGERATION_PROCESS_VS_EMISSIONS = "REFRIGERATION PROCESS VS EMISSION"
// export const REFRIGERANT_TYPE_CONSUMPTIONS_VS_EMISSIONS = "REFRIGERANT TYPE, CONSUMPTIONS VS EMISSIONS"
// export const FUEL_TYPE_CONSUMPTIONS_VS_EMISSIONS = "FUEL TYPE, CONSUMPTIONS VS EMISSIONS"
// export const SPEND_VS_EMISSIONS = "SPEND VS EMISSION";
// export const PURCHASED_ELECTRICITY_CONSUMPTIONS_VS_EMISSIONS = "PURCHASED ELECTRICITY CONSUMPTIONS VS EMISSION";
// export const INVESTMENT_COMPANY_BASED_EMISSIONS = "INVESTMENT COMPANY BASED EMISSION"
// export const EXTRACTION_PRODUCTION_TRANSMISSION_VS_EMISSIONS = "EXTRACTION,PRODUCTION,TRANSMISSION VS EMISSION";
// export const BUSINESS_TRAVEL_VS_EMISSION = "BUSINESS TRAVEL VS EMISSION";
// export const PRODUCT_TYPE_VS_EMISSION = "PRODUCT TYPE VS EMISSION";


import { graphNames_new as graphNames} from "src/constants/appConstants";

export const SET_MASTER_ENTITIES = "SET_MASTER_ENTITIES";
export const SET_ALL_COUNTRIES = "SET_ALL_COUNTRIES";
export const SET_ADD_GRAPH = "SET_ADD_GRAPH";
export const SET_EDIT_GRAPH = "SET_EDIT_GRAPH";

export const SET_SINGLE_VIEW_ENABLE = "SET_SINGLE_VIEW_ENABLE";
export const SET_SINGLE_VIEW_DISABLE = "SET_SINGLE_VIEW_DISABLE";

export const SET_SINGLE_DETAILED = "SET_SINGLE_DETAILED";
export const SET_SINGLE_EXECUTIVE = "SET_SINGLE_EXECUTIVE";

export const REGION_DATA = "REGION_DATA";

// export const SET_EMISSION_REGION_SINGLE = "EMISSION BY REGION";
// export const SET_EMISSION_COUNTRY_SINGLE = "EMISSION BY COUNTRY";

// export const SET_EMISSION_REGION_DETAILED_SINGLE = "EMISSION BY REGION DETAILED";
// export const SET_EMISSION_COUNTRY_DETAILED_SINGLE = "EMISSION BY COUNTRY DETAILED";

// export const SET_EMISSION_SCOPES_SINGLE = "EMISSION SCOPES";
// export const SET_EMISSION_TIMELINE_SINGLE = "EMISSION TIMELINE";
// export const SET_EMISSION_GHG_SINGLE = "GHG WISE EMISSION";
// export const SET_EMISSION_ACTIVITY_SINGLE = "EMISSION ACROSS ACTIVITY";
// export const SET_EMISSION_SUPPLIER_SINGLE = "EMISSION BY SUPPLIER";
// export const SET_EMISSION_SALES_SINGLE = "SALES VS EMISSION";
// export const SET_EMISSION_TRANSPORTATION_SINGLE ="EMISSION ACROSS TRANSPORTATION";

// export const LANES_SINGLE = "LANES VS EMISSION";
// export const CONTINENT_SINGLE = "CONTINENT VS EMISSION";
// export const PROCESS_SINGLE = "PROCESS VS EMISSIONS";
// export const EMISSION_SINGLE = "EMISSION PERFORMANCE";
// export const MODES_SINGLE = "MODES VS EMISSION";
// export const PRODUCT_TYPE_VS_EMISSION_SINGLE = "PRODUCT TYPE VS EMISSIONS";
// export const SUPPLIER_SINGLE = "SUPPLIER VS EMISSIONS";

/*
export const TOTAL_EMISSION_COSTFUEL = "TOTAL_EMISSION_COSTFUEL";
export const NON_SCM_SOURCING_VS_EMISSION = "NON SCM SOURCING VS EMISSIONS";
export const DEDICATED_VEHICLE_TYPE_VS_EMISSION = "DEDICATED VEHICLE TYPE VS EMISSIONS";
export const OUTSOURCED_VEHICLE_TYPE_VS_EMISSION = "OUTSOURCED VEHICLE TYPE VS EMISSIONS";
export const WASTE_PROCESSING_COMPANIES_VS_EMISSION = "WASTE PROCESSING COMPANIES VS EMISSIONS"
export const SOLD_PRODUCTS_VS_EMISSION = "SOLD PRODUCTS VS EMISSIONS";
export const REFRIGERATION_PROCESS_VS_EMISSIONS = "REFRIGERATION PROCESS VS EMISSION"
export const SPEND_VS_EMISSIONS = "SPEND VS EMISSION";
export const PURCHASED_ELECTRICITY_CONSUMPTIONS_VS_EMISSIONS = "PURCHASED ELECTRICITY CONSUMPTION VS EMISSION";
export const INVESTMENT_COMPANY_BASED_EMISSIONS = "INVESTMENT COMPANY BASED EMISSION"
export const EXTRACTION_PRODUCTION_TRANSMISSION_VS_EMISSIONS = "EXTRACTION,PRODUCTION,TRANSMISSION VS EMISSION";
export const BUSINESS_TRAVEL_VS_EMISSION = "BUSINESS TRAVEL VS EMISSION";
export const PRODUCT_TYPE_VS_EMISSION = "PRODUCT TYPE VS EMISSION";

*/

export const EMISSION_BY_REGION = graphNames.EMISSION_BY_REGION;
export const EMISSION_BY_REGION_DETAILED = graphNames.EMISSION_BY_REGION_DETAILED;
export const EMISSION_PERFORMANCE = graphNames.EMISSION_PERFORMANCE;
export const LANES_VS_EMISSION = graphNames.LANES_VS_EMISSION;
export const COST_FUEL_ITEM_SHIPPED_EMISSION = graphNames.COST_FUEL_ITEM_SHIPPED_EMISSION;
export const MODES_VS_EMISSION = graphNames.MODES_VS_EMISSION;
export const TOTAL_SCOPE_1_EMISSION_VS_CATEGORIES = graphNames.TOTAL_SCOPE_1_EMISSION_VS_CATEGORIES;
export const TOTAL_SCOPE_2_EMISSION_VS_CATEGORIES = graphNames.TOTAL_SCOPE_2_EMISSION_VS_CATEGORIES;
export const TOTAL_SCOPE_3_EMISSION_VS_CATEGORIES = graphNames.TOTAL_SCOPE_3_EMISSION_VS_CATEGORIES;
export const PROCESS_VS_EMISSIONS = graphNames.PROCESS_VS_EMISSIONS;
export const SUPPLIER_VS_EMISSIONS = graphNames.SUPPLIER_VS_EMISSIONS;
export const UPSTREAM_NETWORKS_VS_EMISSION = graphNames.UPSTREAM_NETWORKS_VS_EMISSION;
export const DOWNSTREAM_ASSET_TYPE_VS_EMISSION = graphNames.DOWNSTREAM_ASSET_TYPE_VS_EMISSION;
export const DOWNSTREAM_LESSEE_VS_EMISSION = graphNames.DOWNSTREAM_LESSEE_VS_EMISSION;
export const UPSTREAM_ASSET_TYPE_VS_EMISSION = graphNames.UPSTREAM_ASSET_TYPE_VS_EMISSION;
export const UPSTREAM_LESSOR_VS_EMISSION = graphNames.UPSTREAM_LESSOR_VS_EMISSION;
export const RMPO_WISE_EMISSIONS = graphNames.RMPO_WISE_EMISSIONS;
export const NON_SCM_SOURCING_VS_EMISSIONS = graphNames.NON_SCM_SOURCING_VS_EMISSIONS;
export const FRANCHISE_WISE_EMISSION = graphNames.FRANCHISE_WISE_EMISSION;
export const DOWNSTREAM_WASTE_MANAGEMENT_VS_EMISSION = graphNames.DOWNSTREAM_WASTE_MANAGEMENT_VS_EMISSION;
export const UPSTREAM_WASTE_MANAGEMENT_VS_EMISSION = graphNames.UPSTREAM_WASTE_MANAGEMENT_VS_EMISSION;
export const DEDICATED_VEHICLE_TYPE_VS_EMISSIONS = graphNames.DEDICATED_VEHICLE_TYPE_VS_EMISSIONS;
export const OUTSOURCED_VEHICLE_TYPE_VS_EMISSIONS = graphNames.OUTSOURCED_VEHICLE_TYPE_VS_EMISSIONS;
export const WASTE_PROCESSING_COMPANIES_VS_EMISSIONS = graphNames.WASTE_PROCESSING_COMPANIES_VS_EMISSIONS;
export const SOLD_PRODUCTS_VS_EMISSIONS = graphNames.SOLD_PRODUCTS_VS_EMISSIONS;
export const REFRIGERATION_PROCESS_VS_EMISSION = graphNames.REFRIGERATION_PROCESS_VS_EMISSION;
export const REFRIGERANT_TYPE_CONSUMPTIONS_VS_EMISSIONS = graphNames.REFRIGERANT_TYPE_CONSUMPTIONS_VS_EMISSIONS;
export const FUEL_TYPE_CONSUMPTIONS_VS_EMISSIONS = graphNames.FUEL_TYPE_CONSUMPTIONS_VS_EMISSIONS;
export const SPEND_VS_EMISSION = graphNames.SPEND_VS_EMISSION;
export const PURCHASED_ELECTRICITY_CONSUMPTION_VS_EMISSION = graphNames.PURCHASED_ELECTRICITY_CONSUMPTION_VS_EMISSION;
export const INVESTMENT_COMPANY_BASED_EMISSION = graphNames.INVESTMENT_COMPANY_BASED_EMISSION;
export const EXTRACTION_PRODUCTION_TRANSMISSION_VS_EMISSION = graphNames.EXTRACTION_PRODUCTION_TRANSMISSION_VS_EMISSION;
export const PRODUCT_TYPE_VS_EMISSIONS = graphNames.PRODUCT_TYPE_VS_EMISSIONS;
export const BUSINESS_TRAVEL_VS_EMMISSION = graphNames.BUSINESS_TRAVEL_VS_EMMISSION;

export const EMISSION_BY_COUNTRY = graphNames.EMISSION_BY_COUNTRY;
export const EMISSION_BY_COUNTRY_DETAILED = graphNames.EMISSION_BY_COUNTRY_DETAILED;
export const CONTINENT_VS_EMISSION = graphNames.CONTINENT_VS_EMISSION;
export const BU_PERFORMANCE = graphNames.BU_PERFORMANCE;
export const EMISSION_TIMELINE = graphNames.EMISSION_TIMELINE;
export const EMISSION_SCOPES = graphNames.EMISSION_SCOPES;
export const EMISSION_ACROSS_ACTIVITY = graphNames.EMISSION_ACROSS_ACTIVITY;
export const EMISSION_ACROSS_TRANSPORTATION = graphNames.EMISSION_ACROSS_TRANSPORTATION;
export const SALES_BY_EMISSION = graphNames.SALES_BY_EMISSION;
export const GHG_WISE_EMISSION = graphNames.GHG_WISE_EMISSION;
export const EMISSION_BY_SUPPLIER = graphNames.EMISSION_BY_SUPPLIER;
