export default {
    notFound: "/*",
    homePage: "/",
    executive: "/carbon-analytics/executive-summary",
    detailed: "/carbon-analytics/detailed-summary",
    equivalence: "/carbon-analytics/equivalence",
    computation:"/carbon-analytics/computation",
    scope:"/carbon-analytics/computation/scope",
    singleView: "/carbon-analytics/singleview/:id",
    entityManagement:"/entity-management/master/vehicle-entity",
    vehicleMaster : "/entity-management/master/vehicle-entity",
    locationMaster : "/entity-management/master/location-entity",
    scope11 : "/entity-management/transactional/scope-1-1",
    scope12 : "/entity-management/transactional/scope-1-2",
    scope13 : "/entity-management/transactional/scope-1-3",
    scope2 : "/entity-management/transactional/scope-2",
    scope31 : "/entity-management/transactional/scope-3-1",
    scope32 : "/entity-management/transactional/scope-3-2",
    scope33 : "/entity-management/transactional/scope-3-3",
    scope34 : "/entity-management/transactional/scope-3-4",
    scope35 : "/entity-management/transactional/scope-3-5",
    scope36 : "/entity-management/transactional/scope-3-6",
    scope37 : "/entity-management/transactional/scope-3-7",
    scope38 : "/entity-management/transactional/scope-3-8",
    scope39 : "/entity-management/transactional/scope-3-9",
    scope310 : "/entity-management/transactional/scope-3-10",
    scope311 : "/entity-management/transactional/scope-3-11",
    scope312 : "/entity-management/transactional/scope-3-12",
    scope313 : "/entity-management/transactional/scope-3-13",
    scope314 : "/entity-management/transactional/scope-3-14",
    scope315 : "/entity-management/transactional/scope-3-15",
    dataMappingLayer:"/data-mapping-layer/upload",
    rawData:"/data-mapping-layer/rule-selection",
    viewRule:"/data-mapping-layer/view-rule",
    simulator:"/risk-recommendation/simulator"
}