export const DML_SELECTED_FILES = "DML_SELECTED_FILES";
export const DML_SELECTED_ENTITY = "DML_SELECTED_ENTITY";
export const DML_SELECTED_MODE = "DML_SELECTED_MODE";
export const DML_SELECTED_MONTH = "DML_SELECTED_MONTH";
export const DML_SELECTED_YEAR = "DML_SELECTED_YEAR";
export const DML_SELECTED_RULE = "DML_SELECTED_RULE";

